version: "3.1"
services:
  nginx:
    image: nginx:1.15.1-alpine
    container_name: gallery_nginx
    ports:
      - "8080:80"
    expose:
      - "80"
    links:
      - vuex:vuex
      - php:php
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    sysctls:
      - net.core.somaxconn=65536
      - net.ipv4.tcp_syncookies=0

  vuex:
    build:
      context: .
      dockerfile: Dockerfile_node
    image: gallery_vuex
    container_name: gallery_vuex
    ports:
      - "4000:4000"
    expose:
      - "80"
    volumes:
      - ./:/home/gallery
    restart: always
    working_dir: /home/gallery
    tty: true
    command: "sh run.sh"

  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    image: gallery_php
    container_name: gallery_php
    expose:
      - "9000"
    working_dir: /var/www/html
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-fpm.d/www.conf:/usr/local/etc/php/php-fpm.d/www.conf
      - ./php:/var/www/html/php
      - ./static/images:/var/www/html/images
